### ISSUE TITLE
Clearify Strava activity:write in readme 

### ISSUE THREAD

**Issue by RELNO** [alexpryshchepa/nrc2strava#1]
This issue is more to say thanks, excellent work, and the only one that allowed me to escape the NRC cage.. 

It might worth improving the readme, especially this part:
```You need activity:write scope STRAVA token, you can get it by login to website and change the scope in url on strava auth page, then look for token cookie```

It took me some time to figure that one needs to change `activity:write` and then log in. I found the session id only be in the next screen.

**Comment by alexpryshchepa** [comment]
Thanks for the feedback, glad the solution helped not only me. Pushed few updates to README
