### ISSUE TITLE
Nike token is not valid

### ISSUE THREAD

**Issue by ignotas1** [alexpryshchepa/nrc2strava#2]
Hi,

I've tried to use this, however it does not accept Nike token. I found that token is being taken from v2 Nike API, e.g. https://api.nike.com/buy/carts/v2/US/NIKE/NIKECOM, however in the code v3 is used.

Could you guide me and assist on finding valid token?
Thanks

**Comment by ignotas1** [comment]
Ignore. Everything worked out

**Comment by andrewybarra** [comment]
Hi, can you share what was done to authenticate and use the v2 api?
